language: ruby
before_install:
  - gem update --system
  - gem install bundler
rvm:
    - 2.3.8
    - 2.4.6
    - 2.5.5
    - 2.6.3
env:
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=5.1"
  - "RAILS_VERSION=5.2"
matrix:
  fast_finish: true

cache: bundler