language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
env:
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=5.1"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=4.2"
