language: ruby
before_install:
  - gem update --system
  - gem install bundler
rvm:
    - 2.3.8
    - 2.4.6
    - 2.5.5
    - 2.6.3
env:
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=5.1"
  - "RAILS_VERSION=5.2"
  - "RAILS_VERSION=6.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.3.8
      env: RAILS_VERSION=6.0
    - rvm: 2.4.6
      env: RAILS_VERSION=6.0

cache: bundler
