language: ruby
rvm:
  - ruby-head
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.0
env:
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=5.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.10
      env: "RAILS_VERSION=5.0"
    - rvm: 2.4.0
      env: "RAILS_VERSION=4.2"
