sudo: false
language: ruby
before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
env:
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=5.1"
  - "RAILS_VERSION=5.2"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.5.1
      env: "RAILS_VERSION=4.2"
    - rvm: 2.4.4
      env: "RAILS_VERSION=4.2"

cache: bundler