language: ruby
rvm:
    - 2.4.7
    - 2.5.6
    - 2.6.4
env:
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=5.1"
  - "RAILS_VERSION=5.2"
  - "RAILS_VERSION=6.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.3.8
      env: RAILS_VERSION=6.0
    - rvm: 2.4.7
      env: RAILS_VERSION=6.0

cache: bundler
